"""add alerts

Revision ID: ca11b79ae42e
Revises: eefc169f7633
Create Date: 2023-09-04 11:11:16.584497

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "ca11b79ae42e"
down_revision = "eefc169f7633"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255, collation="utf8_bin"), nullable=False),
        sa.Column(
            "project", sa.String(length=255, collation="utf8_bin"), nullable=False
        ),
        sa.Column("object", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project", "name", name="_alert_configs_uc"),
    )
    op.create_table(
        "alert_configs_alert_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.Column("created", mysql.TIMESTAMP(fsp=3), nullable=True),
        sa.Column("last_updated", mysql.TIMESTAMP(fsp=3), nullable=True),
        sa.Column("active", sa.BOOLEAN(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("object", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["alert_configs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "parent_id", name="_alert_configs_alert_states_uc"),
    )
    op.create_table(
        "alert_configs_notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "project", sa.String(length=255, collation="utf8_bin"), nullable=True
        ),
        sa.Column("name", sa.String(length=255, collation="utf8_bin"), nullable=False),
        sa.Column("kind", sa.String(length=255, collation="utf8_bin"), nullable=False),
        sa.Column(
            "message", sa.String(length=255, collation="utf8_bin"), nullable=False
        ),
        sa.Column(
            "severity", sa.String(length=255, collation="utf8_bin"), nullable=False
        ),
        sa.Column("when", sa.String(length=255, collation="utf8_bin"), nullable=False),
        sa.Column(
            "condition", sa.String(length=255, collation="utf8_bin"), nullable=False
        ),
        sa.Column("secret_params", sa.JSON(), nullable=True),
        sa.Column("params", sa.JSON(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("sent_time", mysql.TIMESTAMP(fsp=3), nullable=True),
        sa.Column(
            "status", sa.String(length=255, collation="utf8_bin"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["alert_configs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "name", "parent_id", name="_alert_configs_notifications_uc"
        ),
    )
    op.drop_index("_feature_sets_tags_obj_name_fk", table_name="feature_sets_tags")
    op.drop_index(
        "_feature_vectors_tags_obj_name_fk", table_name="feature_vectors_tags"
    )
    op.drop_index("_functions_tags_obj_name_fk", table_name="functions_tags")
    op.drop_index("_marketplace_sources_uc", table_name="hub_sources")
    op.create_unique_constraint("_hub_sources_uc", "hub_sources", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_hub_sources_uc", "hub_sources", type_="unique")
    op.create_index("_marketplace_sources_uc", "hub_sources", ["name"], unique=False)
    op.create_index(
        "_functions_tags_obj_name_fk", "functions_tags", ["obj_name"], unique=False
    )
    op.create_index(
        "_feature_vectors_tags_obj_name_fk",
        "feature_vectors_tags",
        ["obj_name"],
        unique=False,
    )
    op.create_index(
        "_feature_sets_tags_obj_name_fk",
        "feature_sets_tags",
        ["obj_name"],
        unique=False,
    )
    op.drop_table("alert_configs_notifications")
    op.drop_table("alert_configs_alert_states")
    op.drop_table("alert_configs")
    # ### end Alembic commands ###
